// Sketch-folder files required (generated by train_stress_model.py):
//   - stress_model.h        (C array of the INT8 TFLite model)
//   - scaler_constants.h    (FEAT_MEAN[], FEAT_STD[], TFLITE_INPUT_SCALE,
//                            TFLITE_INPUT_ZERO_POINT, STRESS_LABELS[])
#include <Wire.h>
#include <SPI.h>
#include "MAX30105.h"
#include "arduinoFFT.h"
#include <MPU6050_light.h>
#include <BLEDevice.h>
#include <BLEServer.h>
#include <BLEUtils.h>
#include <BLE2902.h>
#include <Adafruit_GFX.h>
#include <Adafruit_GC9A01A.h>
// ── TFLite Micro ─────────────────────────────────────────────────────────────
#include "tensorflow/lite/micro/micro_interpreter.h"
#include "tensorflow/lite/micro/micro_mutable_op_resolver.h"
#include "tensorflow/lite/schema/schema_generated.h"
#include "stress_model.h"       // generated by train_stress_model.py → output/
#include "scaler_constants.h"   // generated by train_stress_model.py → output/
// DEEP SLEEP
#define SLEEP_POLL_SECONDS   2            // wakeup interval while sleeping
#define S_TO_uS_FACTOR       1000000ULL
#define INACTIVITY_TIMEOUT   15000UL      // ms with no activity → sleep
unsigned long lastActivityTime = 0;

RTC_DATA_ATTR int totalSteps       = 0;   // survives deep sleep
RTC_DATA_ATTR int bootCount        = 0;
RTC_DATA_ATTR int displayRotation  = 0;  // 0 = normal, 2 = flipped 180° (survives sleep)

unsigned long lastPPGNotify = 0;          // throttle raw-PPG BLE to ~40 Hz

// ── TRIPLE-TAP (screen flip) ──────────────────────────────────────────────────
// A "tap" = IR crosses FINGER_ON threshold for 30–500 ms then releases.
// Three taps within TAP_WINDOW_MS flips the display 180° for the person across.
#define TAP_MAX_MS    500UL    // longest contact that still counts as a tap
#define TAP_WINDOW_MS 1500UL   // window in which 3 taps must occur
bool          tapIRprev    = false;
unsigned long tapOnTime    = 0;
int           tapCount     = 0;
unsigned long tapFirstTime = 0;
// GC9A01A DISPLAY — SPI PINS
#define TFT_CS    37
#define TFT_DC    38
#define TFT_RST   39
#define TFT_MOSI  35
#define TFT_SCLK  36
#define TFT_BL    -1   // backlight always on (tie to 3V3) or unused
#define TFT_WIDTH  240
#define TFT_HEIGHT 240

Adafruit_GC9A01A tft(TFT_CS, TFT_DC, TFT_MOSI, TFT_SCLK, TFT_RST);

// COLOR PALETTE
#define COLOR_BG        0x0000   // pure black
#define COLOR_ACCENT    0x07FF   // cyan
#define COLOR_WHITE     0xFFFF
#define COLOR_GREY      0x4208
#define COLOR_LIGHTGREY 0xAD75
#define COLOR_GREEN     0x07E0
#define COLOR_YELLOW    0xFFE0
#define COLOR_RED       0xF800
#define COLOR_ORANGE    0xFD20
#define COLOR_HEART     0xF81F   // magenta/pink
#define COLOR_BLE_ON    0x03FF
#define COLOR_DIVIDER   0x2104
// BLE UUIDs
#define SERVICE_UUID            "19b10000-e8f2-537e-4f6c-d104768a1214"
#define CHAR_UUID_BPM           "19b10001-e8f2-537e-4f6c-d104768a1214"
#define CHAR_UUID_FINGER_STATUS "19b10004-e8f2-537e-4f6c-d104768a1214"
#define CHAR_UUID_SPO2          "19b10005-e8f2-537e-4f6c-d104768a1214"
#define CHAR_UUID_STEPS         "19b10006-e8f2-537e-4f6c-d104768a1214"
#define CHAR_UUID_ACTIVITY      "19b10007-e8f2-537e-4f6c-d104768a1214"
#define CHAR_UUID_PPG           "19b10008-e8f2-537e-4f6c-d104768a1214"
#define CHAR_UUID_STRESS        "19b10009-e8f2-537e-4f6c-d104768a1214"   // NEW

BLEServer*         pServer           = NULL;
BLECharacteristic* pCharBPM          = NULL;
BLECharacteristic* pCharFingerStatus = NULL;
BLECharacteristic* pCharSpO2         = NULL;
BLECharacteristic* pCharSteps        = NULL;
BLECharacteristic* pCharActivity     = NULL;
BLECharacteristic* pCharPPG          = NULL;
BLECharacteristic* pCharStress       = NULL;   // NEW
bool deviceConnected    = false;
bool oldDeviceConnected = false;
// SENSORS
MAX30105 particleSensor;
MPU6050  mpu(Wire);
// MPU6050 — STEP COUNTING & ACTIVITY
String currentActivity = "Resting";
float  oldAccelMag     = 1.0f;
unsigned long lastStepTime = 0;
bool   isMoving        = false;
// MPU6050 — DRIFT SUPPRESSION
// Three-layer defence: hardware DLPF (setup) + IIR software filter + dead zone + hysteresis.
float  filteredAccelMag   = 1.0f;   // IIR low-pass output, seeded at 1 g (gravity)
int    motionConfirmCount = 0;       // consecutive above-threshold samples
int    restConfirmCount   = 0;       // consecutive below-threshold samples
#define ACCEL_LPF_ALPHA   0.15f     // IIR weight on each new sample (lower = smoother / more lag)
#define ACCEL_NOISE_FLOOR 0.04f     // |delta from 1g| below this is treated as exactly zero
#define MOTION_CONFIRM    4          // samples needed to assert  isMoving = true
#define REST_CONFIRM      15         // samples needed to assert  isMoving = false
// FFT — HEART RATE
// Sensor config:  sampleRate=200, sampleAverage=4  → 50 effective sps
// FFT window:     256 samples  → frequency resolution = 50/256 ≈ 0.195 Hz ≈ 11.7 BPM
// Sliding window: 50% overlap  → new BPM result every 128 samples ≈ 2.56 s
#define PULSE_SAMPLES  256
#define SAMPLE_FREQ    50      // effective sps — MUST match sensor config below
#define FFT_HOP        128     // samples between FFT runs (50% overlap)
#define MAX30102_SWAP_CHANNELS  0

arduinoFFT FFT;                // arduinoFFT v1.x object (re-initialised each run)
double redArray[PULSE_SAMPLES];   // circular sample buffer (red channel)
double vReal[PULSE_SAMPLES];      // FFT input (real)
double vImag[PULSE_SAMPLES];      // FFT input (imaginary — zeroed each run)

int    sampleIndex  = 0;       // write pointer into redArray
int    fftHopCount  = 0;       // new samples since last FFT run
bool   bufferFilled = false;   // true once the first 256 samples are in

double beatsPerMinute = 0.0;   // raw FFT peak → BPM
int    beatAvg        = 0;     // IIR-smoothed BPM for display & BLE
int    lastSentBPM    = -1;
// SpO2 + TEMPERATURE
// Method: R = (√Σred_ac² / DC_red) / (√Σir_ac² / DC_ir)
//         SpO2 = -23.3*(R - 0.4) + 100   (Microchip AN1525 approximation)
//         ESpO2 = FSpO2*ESpO2 + (1-FSpO2)*SpO2   (IIR low-pass)
#define SPO2_NUM       100     // accumulation window  (= 2 s at 50 sps)
#define FINGER_ON      50000UL // IR threshold for finger presence
#define TIMETOBOOT_MS  3000    // ignore SpO2 output during sensor warm-up

double avered    = 0.0;        // IIR DC level — red channel
double aveir     = 0.0;        // IIR DC level — IR channel
double sumirrms  = 0.0;        // running  Σ(IR_ac)²
double sumredrms = 0.0;        // running  Σ(red_ac)²
double frate     = 0.95;       // IIR pole for DC tracking filter
double FSpO2     = 0.7;        // SpO2 IIR smoothing weight
float  ESpO2     = 98.0f;      // estimated SpO2 — pre-seeded to plausible value
int    currentSpO2  = 0;
int    lastSentSpO2 = -1;
int    spo2Count    = 0;       // samples accumulated in current window
float  temperature  = 0.0f;    // °C from MAX30102 die temperature sensor
// ── HRV — RR INTERVAL BUFFER ─────────────────────────────────────────────────
// detectPeakAndUpdateRR() fires on each PPG sample.
// computeHRVFeatures()    runs once per 60-second inference cycle.
#define RR_BUFFER_SIZE  60          // last 60 RR intervals ≈ 1 minute at 60 BPM
float  rrIntervals[RR_BUFFER_SIZE]; // RR interval history in milliseconds
int    rrCount       = 0;           // valid intervals accumulated (capped at RR_BUFFER_SIZE)
int    rrWriteIdx    = 0;           // ring-buffer write pointer
unsigned long lastPeakTime = 0;     // timestamp of last detected PPG peak
bool   inPeak        = false;       // true while AC signal is above the rise threshold

float  feat_rmssd = 0.0f;           // root mean square successive differences (ms)
float  feat_sdnn  = 0.0f;           // standard deviation of all NN intervals (ms)
float  feat_pnn50 = 0.0f;           // % successive differences > 50 ms
// ── TFLite Micro — STRESS CLASSIFIER ─────────────────────────────────────────
// tensor_arena is allocated in PSRAM via the section attribute.
// 8 KB is ample for a Dense(16)→Dense(8)→Dense(3) INT8 model (~3-5 KB model size).
constexpr int TENSOR_ARENA_SIZE = 8 * 1024;
static uint8_t tensor_arena[TENSOR_ARENA_SIZE]
    __attribute__((aligned(16)));   // keep in SRAM; move to PSRAM if linker complains
tflite::MicroInterpreter* tflite_interpreter = nullptr;
TfLiteTensor*             tflite_input       = nullptr;
TfLiteTensor*             tflite_output      = nullptr;
String stressLabel       = "---";   // current inference result shown on screen
String lastSentStress    = "";      // tracks last BLE-notified value
String lastDisplayStress = "";      // tracks last value drawn on screen
unsigned long lastInferTime = 0;    // global — survives loop(), safe after deep-sleep wakeup

// FINGER / DISPLAY STATE
bool   fingerDetected     = false;
bool   lastFingerDetected = false;
bool   heartState         = false;   // toggled for heart animation
unsigned long lastHeartFlash = 0;

int    lastDisplayBPM    = -1;
int    lastDisplaySpO2   = -1;
bool   lastDisplayFinger = false;
bool   lastDisplayMoving = false;
bool   lastDisplayBLE    = false;
unsigned long lastDisplayUpdate = 0;
// BLE CALLBACKS
class MyServerCallbacks : public BLEServerCallbacks {
    void onConnect(BLEServer* pServer)    { deviceConnected = true;  }
    void onDisconnect(BLEServer* pServer) { deviceConnected = false; }
};
// DISPLAY HELPERS
// setTextColor(fg, bg) fills each character's background pixel-by-pixel together
// with the foreground — no separate fillRect needed, so no black-flash before text.
void printCenteredText(String text, int y, int size, uint16_t color) {
    tft.setTextSize(size);
    tft.setTextColor(color, COLOR_BG);   // bg fill eliminates the clear→draw flash
    int16_t x1, y1;
    uint16_t w, h;
    tft.getTextBounds(text, 0, 0, &x1, &y1, &w, &h);
    tft.setCursor(120 - (w / 2), y);
    tft.print(text);
}
void updateHeartIcon(bool beat) {
    const int hx = 65, hy = 95;
    if (fingerDetected) {
        // Draw directly in the new colour — no fillRect beforehand.
        // Because the shape never changes, overwriting with a new colour is
        // instantaneous and removes the black-flash between every heartbeat.
        uint16_t color = beat ? COLOR_HEART : 0x2000;
        tft.fillCircle(hx - 4, hy,     4, color);
        tft.fillCircle(hx + 4, hy,     4, color);
        tft.fillTriangle(hx - 8, hy + 2, hx + 8, hy + 2, hx, hy + 10, color);
    } else {
        // Finger removed — only then clear the icon area
        tft.fillRect(hx - 10, hy - 10, 20, 20, COLOR_BG);
    }
}
void drawStaticLayout() {
    tft.fillScreen(COLOR_BG);
    tft.drawCircle(120, 120, 118, COLOR_DIVIDER);
    tft.drawLine(50, 65, 190, 65, COLOR_DIVIDER);
}
void updateStatusDisplay(bool finger, bool moving, bool ble) {
    tft.fillRect(40, 25, 160, 35, COLOR_BG);
    tft.fillCircle(80,  35, 5, finger ? COLOR_GREEN  : COLOR_GREY);
    tft.fillCircle(120, 35, 5, ble    ? COLOR_BLE_ON : COLOR_GREY);
    tft.fillCircle(160, 35, 5, moving ? COLOR_ORANGE : COLOR_GREEN);
    tft.setTextSize(1);
    tft.setTextColor(COLOR_LIGHTGREY, COLOR_BG);   // bg fill — no pre-clear needed
    tft.setCursor(70,  45); tft.print("FING");
    tft.setCursor(112, 45); tft.print("BLE");
    tft.setCursor(150, 45); tft.print("MOVE");
}
// Draws BPM (large centre), SpO2, and temperature.
// ── Flicker-free strategy ────────────────────────────────────────────────────
// All text uses setTextColor(fg, COLOR_BG) so each character's background is
// filled simultaneously with the foreground — no separate fillRect → no flash.
// Fixed-width number formats ensure a shorter number never leaves ghost digits
// from a previously wider one (e.g. "100" → " 72" with leading-space erase).
// The large fillRect is kept ONLY for state transitions (finger on ↔ off)
// which are infrequent enough that a one-time clear is acceptable.
void updateBPMAndSpO2Display(int bpm, int spo2, float temp) {
    if (fingerDetected && bpm > 0) {
        // ── BPM — size-5, 3 chars wide, fixed left edge at x=75 ─────────────
        // Size-5 char = 30 px wide × 40 px tall.  3 chars = 90 px → centred.
        // "%3d" right-justifies: " 72" or "100" — leading space erases old digit.
        // Targeted mini-clear (90×42 px) replaces the original 160×100 fillRect,
        // cutting flash duration by ~95 %.
        char bpmStr[8];
        sprintf(bpmStr, "%3d", bpm);
        tft.fillRect(75, 82, 90, 42, COLOR_BG);      // clear only the number box
        tft.setTextSize(5);
        tft.setTextColor(COLOR_WHITE, COLOR_BG);
        tft.setCursor(75, 82);
        tft.print(bpmStr);

        // ── SpO2 — size-2, fixed-width "SpO2: XXX%" (10 chars = 120 px) ─────
        // "%4d" gives " 98" or "100", so total string is always 10 chars.
        // No fillRect — setTextColor bg fill handles it completely.
        char spo2Str[16];
        sprintf(spo2Str, "SpO2:%4d%%", spo2 > 0 ? spo2 : 0);
        tft.setTextSize(2);
        tft.setTextColor(COLOR_ACCENT, COLOR_BG);
        tft.setCursor(60, 138);   // 10 chars × 12 px = 120 px → left edge at 60
        tft.print(spo2Str);

        // ── Temperature — size-1, shown once a valid reading exists ──────────
        if (temp > 0.0f) {
            char tempStr[20];
            sprintf(tempStr, "Temp: %5.1f C", temp);  // "Temp:  36.5 C" = 13 chars
            tft.setTextSize(1);
            tft.setTextColor(COLOR_LIGHTGREY, COLOR_BG);
            tft.setCursor(81, 160);   // 13 chars × 6 px = 78 px → left edge at 81
            tft.print(tempStr);
        }
    } else {
        // ── No finger / no BPM yet — state-change clear is acceptable ────────
        tft.fillRect(40, 75, 160, 100, COLOR_BG);
        tft.setTextSize(5);
        tft.setTextColor(COLOR_GREY, COLOR_BG);
        tft.setCursor(90, 90);   // "--" = 2 chars × 30 px = 60 px → left at 90
        tft.print("--");
        if (!fingerDetected) {
            tft.setTextSize(1);
            tft.setTextColor(COLOR_LIGHTGREY, COLOR_BG);
            tft.setCursor(84, 148);  // "Place finger" = 12 chars × 6 px = 72 px
            tft.print("Place finger");
        }
    }
}
void updateActivityDisplay() {
    String actInfo = String(totalSteps) + " steps | " + currentActivity;
    static String lastActInfo = "";
    if (actInfo == lastActInfo) return;   // nothing changed — skip entirely
    lastActInfo = actInfo;
    // Pad to 26 chars so shorter strings overwrite longer ones without fillRect.
    // A space drawn with setTextColor(fg, bg) fills with COLOR_BG — acts as eraser.
    while ((int)actInfo.length() < 26) actInfo += ' ';
    tft.setTextSize(1);
    tft.setTextColor(COLOR_ACCENT, COLOR_BG);
    int16_t x1, y1; uint16_t w, h;
    tft.getTextBounds(actInfo, 0, 0, &x1, &y1, &w, &h);
    tft.setCursor(120 - (w / 2), 215);
    tft.print(actInfo);
}
// ── Stress label display (y=178–200, between temperature and activity bar) ───
// Green = Low, Yellow = Moderate, Red = High.
// Uses fixed-width padding so a shorter label erases a longer one via bg fill.
void updateStressDisplay() {
    if (fingerDetected && stressLabel != "---") {
        uint16_t col = (stressLabel == "High")     ? COLOR_RED    :
                       (stressLabel == "Moderate") ? COLOR_YELLOW : COLOR_GREEN;
        String msg = "STRESS: " + stressLabel;
        while ((int)msg.length() < 20) msg += ' ';  // pad to erase previous longer label
        tft.setTextSize(1);
        tft.setTextColor(col, COLOR_BG);
        int16_t x1, y1; uint16_t w, h;
        tft.getTextBounds(msg, 0, 0, &x1, &y1, &w, &h);
        tft.setCursor(120 - (w / 2), 180);
        tft.print(msg);
    } else {
        // Clear the row when stress is unknown or finger is removed
        tft.fillRect(40, 178, 160, 22, COLOR_BG);
    }
}
// Only redraws the regions that have actually changed — zero wasted SPI bandwidth.
void updateDisplay(unsigned long now) {
    bool statusChanged = (fingerDetected  != lastDisplayFinger ||
                          isMoving        != lastDisplayMoving  ||
                          deviceConnected != lastDisplayBLE);
    if (statusChanged) {
        updateStatusDisplay(fingerDetected, isMoving, deviceConnected);
        if (fingerDetected != lastDisplayFinger)
            updateBPMAndSpO2Display(beatAvg, currentSpO2, temperature);
        lastDisplayFinger = fingerDetected;
        lastDisplayMoving = isMoving;
        lastDisplayBLE    = deviceConnected;
    }
    if (fingerDetected &&
        (beatAvg != lastDisplayBPM || currentSpO2 != lastDisplaySpO2)) {
        updateBPMAndSpO2Display(beatAvg, currentSpO2, temperature);
        lastDisplayBPM  = beatAvg;
        lastDisplaySpO2 = currentSpO2;
    }
    // Redraw stress label whenever it changes (set by runStressInference,
    // reset to "---" by resetMeasurements when finger is removed)
    if (stressLabel != lastDisplayStress) {
        updateStressDisplay();
        lastDisplayStress = stressLabel;
    }
    if (now - lastDisplayUpdate > 1000) {
        updateActivityDisplay();
        lastDisplayUpdate = now;
    }
}
// MEASUREMENT RESET — called when finger is removed
void resetMeasurements() {
    beatsPerMinute = 0.0;  beatAvg = 0;    lastSentBPM  = -1;
    currentSpO2    = 0;                    lastSentSpO2 = -1;
    ESpO2          = 98.0f;
    avered = 0.0;  aveir = 0.0;
    sumirrms = 0.0;  sumredrms = 0.0;  spo2Count = 0;
    sampleIndex = 0;  fftHopCount = 0;  bufferFilled = false;
    memset(redArray, 0, sizeof(redArray));
    temperature = 0.0f;
    // Reset HRV state
    rrCount      = 0;
    rrWriteIdx   = 0;
    lastPeakTime = 0;
    inPeak       = false;
    feat_rmssd   = 0.0f;
    feat_sdnn    = 0.0f;
    feat_pnn50   = 0.0f;
    // Reset stress display
    stressLabel       = "---";
    lastSentStress    = "";
    lastDisplayStress = "";
}
// HRV — PEAK DETECTION & FEATURE COMPUTATION

// Called once per PPG sample inside the FIFO drain loop.
// Uses the already-updated avered DC baseline to isolate the AC component,
// then detects each systolic peak with a simple hysteresis threshold.
// Rise threshold (5000 counts) and fall threshold (3000 counts) are suitable
// for the MAX30102 at full LED drive (0xFF); lower them by ~20% if you reduce
// ledBrightness in particleSensor.setup().
void detectPeakAndUpdateRR(double sample, unsigned long nowMs) {
    double acSample = sample - avered;
    if (!inPeak && acSample > 300.0) {
        inPeak = true;
        if (lastPeakTime > 0) {
            float rr = (float)(nowMs - lastPeakTime);
            if (rr > 300.0f && rr < 2000.0f) {
                bool consistent = true;
                if (rrCount > 0) {
                    float lastRR = rrIntervals[(rrWriteIdx - 1 + RR_BUFFER_SIZE) % RR_BUFFER_SIZE];
                    if (fabsf(rr - lastRR) / lastRR > 0.50f) consistent = false;
                }
                if (consistent || rrCount == 0) {
                    rrIntervals[rrWriteIdx % RR_BUFFER_SIZE] = rr;
                    rrWriteIdx++;
                    if (rrCount < RR_BUFFER_SIZE) rrCount++;
                }}}
        lastPeakTime = nowMs;}
    if (acSample < 100.0) inPeak = false;}
void computeHRVFeatures() {
    if (rrCount < 10) return;
    int n = min(rrCount, RR_BUFFER_SIZE);
    // SDNN — standard deviation of all NN intervals
    float mean = 0.0f;
    for (int i = 0; i < n; i++) mean += rrIntervals[i];
    mean /= (float)n;
    float variance = 0.0f;
    for (int i = 0; i < n; i++) variance += powf(rrIntervals[i] - mean, 2.0f);
    feat_sdnn = sqrtf(variance / (float)n);
    // RMSSD — root mean square successive differences
    // pNN50  — fraction (%) of successive differences > 50 ms
    float sumSqDiff = 0.0f;
    int   pnn50count = 0;
    for (int i = 1; i < n; i++) {
        float diff = rrIntervals[i] - rrIntervals[i - 1];
        sumSqDiff += diff * diff;
        if (fabsf(diff) > 50.0f) pnn50count++;
    }
    feat_rmssd = sqrtf(sumSqDiff / (float)(n - 1));
    feat_pnn50 = (float)pnn50count / (float)(n - 1) * 100.0f;
}
// TFLite Micro — INIT & INFERENCE
// Loads the INT8 model from stress_model.h, registers only the four ops the
// generated model uses, and allocates the tensor arena.
// Must be called once at the end of setup().
void initTFLite() {
    static tflite::MicroMutableOpResolver<4> resolver;
    resolver.AddFullyConnected();
    resolver.AddSoftmax();
    resolver.AddRelu();
    resolver.AddDequantize();
    const tflite::Model* model_data = tflite::GetModel(stress_model_tflite);
    if (model_data->version() != TFLITE_SCHEMA_VERSION) {
        Serial.println("[TFLite] ERROR: model schema version mismatch!");
        return;
    }
    static tflite::MicroInterpreter static_interp(
        model_data, resolver, tensor_arena, TENSOR_ARENA_SIZE);
    tflite_interpreter = &static_interp;

    TfLiteStatus alloc_status = tflite_interpreter->AllocateTensors();
    if (alloc_status != kTfLiteOk) {
        Serial.println("[TFLite] ERROR: AllocateTensors() failed — arena too small?");
        return;
    }
    tflite_input  = tflite_interpreter->input(0);
    tflite_output = tflite_interpreter->output(0);

    Serial.printf("[TFLite] Stress model ready. Arena used: %u bytes\n",
                  (unsigned)tflite_interpreter->arena_used_bytes());
}
// Runs one forward pass of the stress classifier.
// Inputs (6 features) are Z-score normalised then quantised to INT8 using
// the scale/zero-point from scaler_constants.h — both generated by the
// same Python training script so they are always in sync.
// Output is the argmax of 3 INT8 logits → index into STRESS_LABELS[].
// Guards: needs ≥10 RR intervals and a valid BPM to proceed.
void runStressInference() {
    if (tflite_interpreter == nullptr) return;
    if (rrCount < 10 || beatAvg == 0)  return;
    // Activity encoding matches the training script: 0=Resting, 1=Walking, 2=Running
    float actEnc = (currentActivity == "Running") ? 2.0f :
                   (currentActivity == "Walking")  ? 1.0f : 0.0f;
    float raw[6] = { feat_rmssd,
                     feat_sdnn,
                     feat_pnn50,
                     (float)beatAvg,
                     (float)currentSpO2,
                     actEnc };
    // Normalise each feature then quantise to INT8
    for (int i = 0; i < 6; i++) {
        float normalised = (raw[i] - FEAT_MEAN[i]) / FEAT_STD[i];
        tflite_input->data.int8[i] = (int8_t)(
            normalised / TFLITE_INPUT_SCALE + TFLITE_INPUT_ZERO_POINT);
    }
    if (tflite_interpreter->Invoke() != kTfLiteOk) {
        Serial.println("[TFLite] ERROR: Invoke() failed.");
        return;
    }
    // Argmax over 3 INT8 output logits
    int8_t best = tflite_output->data.int8[0];
    int    pred = 0;
    for (int i = 1; i < 3; i++) {
        if (tflite_output->data.int8[i] > best) {
            best = tflite_output->data.int8[i];
            pred = i;
        }
    }
    stressLabel = String(STRESS_LABELS[pred]);
    // BLE notify if connected and value changed
    if (deviceConnected && stressLabel != lastSentStress) {
        pCharStress->setValue(stressLabel.c_str());
        pCharStress->notify();
        lastSentStress = stressLabel;
    }
    Serial.printf("[AI]   Stress=%-8s  RMSSD=%5.1f  SDNN=%5.1f  pNN50=%5.1f\n",
                  stressLabel.c_str(), feat_rmssd, feat_sdnn, feat_pnn50);
}
// DEEP SLEEP
void goToSleep() {
    Serial.println("Inactivity timeout — entering deep sleep.");
    tft.fillScreen(COLOR_BG);
    printCenteredText("SLEEPING",     105, 2, COLOR_GREY);
    printCenteredText("Place finger", 135, 1, COLOR_LIGHTGREY);
    printCenteredText("to wake",      150, 1, COLOR_LIGHTGREY);
    delay(400);
    particleSensor.shutDown();
    bootCount++;
    Serial.printf("Boot count: %d\n", bootCount);
    esp_sleep_enable_timer_wakeup(SLEEP_POLL_SECONDS * S_TO_uS_FACTOR);
    esp_deep_sleep_start();
}
// Runs at the very top of setup() on a timer-wakeup.
// Boots only Wire + sensor; if no finger → back to sleep, never reaches full init.
void quickFingerCheckOrSleep() {
    Wire.begin(8, 9);
    if (!particleSensor.begin()) {
        esp_sleep_enable_timer_wakeup(SLEEP_POLL_SECONDS * S_TO_uS_FACTOR);
        esp_deep_sleep_start();
    }
    particleSensor.setup();  // default config sufficient for a presence check
    delay(100);              // let LEDs/ADC settle
    uint32_t irVal = 0;
    for (int i = 0; i < 10; i++) {
        particleSensor.check();
        delay(20);
        if (particleSensor.available()) {
            irVal = particleSensor.getIR();
            particleSensor.nextSample();
            break;
        }
    }
    if (irVal < 5000) {
        particleSensor.shutDown();
        esp_sleep_enable_timer_wakeup(SLEEP_POLL_SECONDS * S_TO_uS_FACTOR);
        esp_deep_sleep_start();
    }
    // Finger present → fall through; setup() will do the full initialisation
    Serial.println("Finger detected on timer-wakeup — full boot resuming.");
}
// SETUP
void setup() {
    Serial.begin(115200);
    delay(500);

    // Handle timer-wakeup before anything expensive is initialised
    esp_sleep_wakeup_cause_t wakeReason = esp_sleep_get_wakeup_cause();
    if (wakeReason == ESP_SLEEP_WAKEUP_TIMER) {
        Serial.println("Timer wakeup — quick finger check...");
        quickFingerCheckOrSleep();  // returns ONLY if finger is present
    }
    delay(1500);
    // ── Display ────────────────────────────────────────────────────────────
    tft.begin();
    tft.setRotation(displayRotation);   // 0 = normal, 2 = flipped (restored from RTC after sleep)
    tft.fillScreen(COLOR_BG);

    if (wakeReason == ESP_SLEEP_WAKEUP_TIMER) {
        Serial.println("Woke from sleep — finger present, continuing boot.");
    } else {
        Serial.println("Cold boot.");
        printCenteredText("VITAL SENSE",        100, 2, COLOR_ACCENT);
        printCenteredText("Booting Systems...", 130, 1, COLOR_LIGHTGREY);
        delay(1000);
    }
    // ── BLE ────────────────────────────────────────────────────────────────
    BLEDevice::init("Stress_Monitor");
    pServer = BLEDevice::createServer();
    pServer->setCallbacks(new MyServerCallbacks());

    BLEService* pService = pServer->createService(SERVICE_UUID);

    pCharBPM = pService->createCharacteristic(CHAR_UUID_BPM,
        BLECharacteristic::PROPERTY_READ | BLECharacteristic::PROPERTY_NOTIFY);
    pCharBPM->addDescriptor(new BLE2902());

    pCharFingerStatus = pService->createCharacteristic(CHAR_UUID_FINGER_STATUS,
        BLECharacteristic::PROPERTY_READ | BLECharacteristic::PROPERTY_NOTIFY);
    pCharFingerStatus->addDescriptor(new BLE2902());

    pCharSpO2 = pService->createCharacteristic(CHAR_UUID_SPO2,
        BLECharacteristic::PROPERTY_READ | BLECharacteristic::PROPERTY_NOTIFY);
    pCharSpO2->addDescriptor(new BLE2902());

    pCharSteps = pService->createCharacteristic(CHAR_UUID_STEPS,
        BLECharacteristic::PROPERTY_READ | BLECharacteristic::PROPERTY_NOTIFY);
    pCharSteps->addDescriptor(new BLE2902());

    pCharActivity = pService->createCharacteristic(CHAR_UUID_ACTIVITY,
        BLECharacteristic::PROPERTY_READ | BLECharacteristic::PROPERTY_NOTIFY);
    pCharActivity->addDescriptor(new BLE2902());

    pCharPPG = pService->createCharacteristic(CHAR_UUID_PPG,
        BLECharacteristic::PROPERTY_READ | BLECharacteristic::PROPERTY_NOTIFY);
    pCharPPG->addDescriptor(new BLE2902());

    // NEW: Stress characteristic — notifies "Low", "Moderate", or "High"
    pCharStress = pService->createCharacteristic(CHAR_UUID_STRESS,
        BLECharacteristic::PROPERTY_READ | BLECharacteristic::PROPERTY_NOTIFY);
    pCharStress->addDescriptor(new BLE2902());

    pService->start();
    BLEAdvertising* pAdv = BLEDevice::getAdvertising();
    pAdv->addServiceUUID(SERVICE_UUID);
    pAdv->setScanResponse(false);
    pAdv->setMinPreferred(0x0);
    BLEDevice::startAdvertising();

    // ── MAX30102  (I2C bus: SDA=GPIO8, SCL=GPIO9) ─────────────────────────
    // MPU6050 shares the same bus (address 0x68, AD0 pin low).
    // Wire.begin(SDA, SCL) — confirmed matches schematic and PCB routing.
    Wire.begin(8, 9);
    if (!particleSensor.begin(Wire, I2C_SPEED_FAST)) {
        tft.fillScreen(COLOR_BG);
        printCenteredText("SENSOR ERROR", 110, 2, COLOR_RED);
        printCenteredText("Check Wiring", 140, 1, COLOR_WHITE);
        while (1) delay(1000);
    }
    particleSensor.wakeUp();
    // sampleRate=200 / sampleAverage=4  → 50 effective sps  = SAMPLE_FREQ
    // This MUST be kept in sync with the #define SAMPLE_FREQ 50 above.
    particleSensor.setup(
        0xFF,   // ledBrightness: both channels full drive for best SNR
        4,      // sampleAverage: 4 × hardware average → 50 sps effective
        2,      // ledMode: Red + IR
        200,    // sampleRate: 200 Hz (raw, before averaging)
        411,    // pulseWidth: 411 µs — maximum ADC integration → best SNR
        16384   // adcRange: 16384 counts full scale
    );
    // Equalise both LED drive currents so the Microchip AN1525 R→SpO2
    // calibration polynomial is valid (derived with matched LED amplitudes).
    particleSensor.setPulseAmplitudeRed(0xFF);
    particleSensor.setPulseAmplitudeIR(0xFF);
    particleSensor.setPulseAmplitudeGreen(0);
    particleSensor.enableDIETEMPRDY();   // enable die temperature measurement

    // ── MPU6050 ────────────────────────────────────────────────────────────
    if (mpu.begin() == 0) {
        delay(250);        // let sensor settle before capturing calibration samples
        mpu.calcOffsets(); // ~3000-sample average — keep PCB perfectly still here
    }
    // Enable the MPU6050 on-chip digital low-pass filter.
    // Value 5 → 10 Hz bandwidth for both gyro and accel.
    // This kills electrical and mechanical vibration noise at the hardware level
    // before the data ever reaches the sketch — the most effective single fix.
    //   0 = 260 Hz (off)   3 = 44 Hz   6 = 5 Hz
    //   1 = 184 Hz          4 = 21 Hz
    //   2 =  94 Hz          5 = 10 Hz  ← chosen
    Wire.beginTransmission(0x68); 
    Wire.write(0x1A);             
    Wire.write(5);                
    Wire.endTransmission();
    delay(800);

    // ── TFLite Micro — load stress model ───────────────────────────────────
    initTFLite();

    // Initial render
    drawStaticLayout();
    updateStatusDisplay(false, false, false);
    updateBPMAndSpO2Display(0, 0, 0.0f);
    updateHeartIcon(false);
    lastActivityTime = millis();
}
// LOOP
void loop() {
    unsigned long now = millis();
    // ── 1. BLE reconnection management ────────────────────────────────────
    if (!deviceConnected && oldDeviceConnected) {
        delay(500);
        pServer->startAdvertising();
        oldDeviceConnected = deviceConnected;
    }
    if (deviceConnected && !oldDeviceConnected) {
        oldDeviceConnected = deviceConnected;
    }
    // ── 2. MPU6050: step counting + activity classification ────────────────
    mpu.update();
    float ax = mpu.getAccX();
    float ay = mpu.getAccY();
    float az = mpu.getAccZ();
    float accelMag = sqrtf(ax*ax + ay*ay + az*az);

    // ── Layer 2: IIR software low-pass filter ─────────────────────────────
    // Complements the hardware DLPF by smoothing any residual sample-to-sample
    // jitter.  Alpha = 0.15 keeps ~85 % of the previous output each tick, so a
    // single noisy spike cannot push the filtered value across any threshold.
    filteredAccelMag = ACCEL_LPF_ALPHA * accelMag
                     + (1.0f - ACCEL_LPF_ALPHA) * filteredAccelMag;

    // Step detection: rising edge on the *filtered* magnitude — both sides of
    // the comparison use filteredAccelMag so the edge is noise-free.
    if (filteredAccelMag > 1.25f && oldAccelMag <= 1.25f) {
        if (now - lastStepTime > 300) {
            totalSteps++;
            lastStepTime = now;
            if (deviceConnected) {
                pCharSteps->setValue(String(totalSteps).c_str());
                pCharSteps->notify();
            }
        }
    }
    oldAccelMag = filteredAccelMag;   // store filtered, not raw, for next edge-detect

    // ── Layer 3: dead zone ────────────────────────────────────────────────
    // Any deviation from 1 g smaller than ACCEL_NOISE_FLOOR is collapsed to
    // zero.  This is the direct fix for phantom motion while the PCB is still:
    // the remaining post-DLPF noise (typically < 0.02 g) never reaches the
    // Walking/Running/isMoving thresholds.
    float delta = fabsf(filteredAccelMag - 1.0f);
    if (delta < ACCEL_NOISE_FLOOR) delta = 0.0f;

    String newActivity = "Resting";
    if      (delta > 0.15f && delta < 0.6f) newActivity = "Walking";
    else if (delta >= 0.6f)                 newActivity = "Running";

    if (newActivity != currentActivity) {
        currentActivity = newActivity;
        if (deviceConnected) {
            pCharActivity->setValue(currentActivity.c_str());
            pCharActivity->notify();
        }
    }

    // ── Layer 4: hysteresis ───────────────────────────────────────────────
    // isMoving only flips after MOTION_CONFIRM consecutive above-threshold
    // samples (fast onset) or REST_CONFIRM consecutive below-threshold samples
    // (slow release).  A single noise spike can never change the flag.
    if (delta > 0.25f) {
        restConfirmCount = 0;
        if (++motionConfirmCount >= MOTION_CONFIRM) isMoving = true;
    } else {
        motionConfirmCount = 0;
        if (++restConfirmCount >= REST_CONFIRM)     isMoving = false;
    }

    // ── 3. MAX30102: drain FIFO (up to 32 samples buffered by hardware) ───
    particleSensor.check();
    while (particleSensor.available()) {
        // MH-ET LIVE MAX30102 board has Red/IR channels physically swapped:
        //   getFIFOIR()  → actually outputs Red LED data
        //   getFIFORed() → actually outputs IR  LED data
        #if MAX30102_SWAP_CHANNELS
        uint32_t red = particleSensor.getFIFOIR();   // swapped board: IR pin = Red data
        uint32_t ir  = particleSensor.getFIFORed();  // swapped board: Red pin = IR data
        #else
        uint32_t red = particleSensor.getFIFORed();  // standard board  
        uint32_t ir  = particleSensor.getFIFOIR();
        #endif

        // ── Triple-tap detection: 3 quick touches → flip display 180° ───────
        // Uses raw IR value directly (before the fingerDetected debounce) so
        // short taps that would reset fingerDetected are still counted.
        // A tap = IR rises above FINGER_ON for 30–500 ms, then falls.
        {
            unsigned long tNow  = millis();
            bool          irOn  = (ir > FINGER_ON);
            if (irOn && !tapIRprev) {
                // Rising edge — start timing the contact
                tapOnTime = tNow;
            } else if (!irOn && tapIRprev) {
                // Falling edge — measure duration
                unsigned long dur = tNow - tapOnTime;
                if (dur >= 30 && dur < TAP_MAX_MS) {
                    // Valid tap duration
                    if (tapCount == 0 || tNow - tapFirstTime <= TAP_WINDOW_MS) {
                        if (tapCount == 0) tapFirstTime = tNow;
                        tapCount++;
                    } else {
                        // Window expired — restart count with this tap
                        tapCount    = 1;
                        tapFirstTime = tNow;
                    }
                    Serial.printf("[TAP]  count=%d  dur=%lu ms\n", tapCount, dur);
                    if (tapCount >= 3) {
                        // ── FLIP ──────────────────────────────────────────
                        displayRotation = (displayRotation == 0) ? 2 : 0;
                        tft.setRotation(displayRotation);
                        drawStaticLayout();
                        // Force full redraw of all regions in new orientation
                        updateStatusDisplay(fingerDetected, isMoving, deviceConnected);
                        updateBPMAndSpO2Display(beatAvg, currentSpO2, temperature);
                        updateHeartIcon(heartState);
                        updateActivityDisplay();
                        updateStressDisplay();
                        // Sync "last drawn" trackers so updateDisplay doesn't re-clear
                        lastDisplayFinger = fingerDetected;
                        lastDisplayMoving = isMoving;
                        lastDisplayBLE    = deviceConnected;
                        lastDisplayBPM    = beatAvg;
                        lastDisplaySpO2   = currentSpO2;
                        lastDisplayStress = stressLabel;
                        lastActivityTime  = tNow;   // reset inactivity timer
                        tapCount = 0;
                        Serial.printf("[TAP]  Triple-tap → rotation %d\n", displayRotation);
                    }
                } else if (dur >= TAP_MAX_MS) {
                    tapCount = 0;   // long press (real measurement) resets counter
                }
            }
            tapIRprev = irOn;
        }

        // ── Finger detection ──────────────────────────────────────────────
        bool newFinger = (ir > FINGER_ON);

        if (newFinger != fingerDetected) {
            fingerDetected = newFinger;

            if (deviceConnected) {
                pCharFingerStatus->setValue(fingerDetected ? "1" : "0");
                pCharFingerStatus->notify();
            }
            if (!fingerDetected) {
                // Finger removed: clear all running state (including HRV + stress)
                resetMeasurements();
                lastDisplayBPM  = -1;
                lastDisplaySpO2 = -1;
                updateBPMAndSpO2Display(0, 0, 0.0f);
                updateHeartIcon(false);
            }
        }
        if (fingerDetected) {
            double fred = (double)red;
            double fir  = (double)ir;

            // ── SpO2: IIR DC tracking + AC RMS accumulation ───────────────
            // avered / aveir track the slowly-varying DC baseline (frate=0.95).
            // Subtracting DC from each sample gives the AC (pulsatile) component.
            avered    = avered * frate + fred * (1.0 - frate);
            aveir     = aveir  * frate + fir  * (1.0 - frate);
            sumredrms += (fred - avered) * (fred - avered);
            sumirrms  += (fir  - aveir)  * (fir  - aveir);
            spo2Count++;
            // ── FFT heart rate: store sample in circular buffer ───────────
            redArray[sampleIndex] = fred;

            // ── HRV peak detection (uses avered, updated just above) ───────
            // Must be called after avered is updated so the AC extraction is
            // based on the current DC level, not the previous sample's level.
            detectPeakAndUpdateRR(fred, now);

            sampleIndex = (sampleIndex + 1) % PULSE_SAMPLES;
            fftHopCount++;
            if (!bufferFilled && sampleIndex == 0) bufferFilled = true;

            // ── Raw PPG stream over BLE at ~40 Hz ─────────────────────────
            if (deviceConnected && (now - lastPPGNotify >= 25)) {
                pCharPPG->setValue(String(ir).c_str());
                pCharPPG->notify();
                lastPPGNotify = now;
            }
            // ── Compute SpO2 every SPO2_NUM samples (≈2 s) ───────────────
            if (spo2Count >= SPO2_NUM && millis() > TIMETOBOOT_MS) {
                if (avered > 1000.0 && aveir > 1000.0) {
                    // Perfusion index = AC amplitude / DC level for each channel
                    double pi_red = sqrt(sumredrms) / avered;
                    double pi_ir  = sqrt(sumirrms)  / aveir;
                    // Signal quality gate — valid finger contact gives PI between 0.1% and 15%
                    // Outside this range the finger has moved or signal is noise
                    bool signalOk = (pi_red > 0.001 && pi_red < 0.15 &&
                                    pi_ir  > 0.001 && pi_ir  < 0.15);
                    if (signalOk) {
                        double R = pi_red / pi_ir;
                        // R must sit in the physiological window (SpO2 roughly 70–100%)
                        // Outside this window the reading is invalid — hold last good value
                        if (R >= 0.3 && R <= 1.3) {
                            // Quadratic calibration — more accurate than linear across full range
                            // Source: Maxim AN6291 / Elgendi et al. 2019
                            double spo2Raw = -45.060 * R * R + 30.354 * R + 94.845;
                            // Only accept physiologically plausible output
                            if (spo2Raw >= 85.0 && spo2Raw <= 100.0) {
                                ESpO2 = (float)(FSpO2 * ESpO2 + (1.0 - FSpO2) * spo2Raw);
                                currentSpO2 = (int)round(ESpO2);
                                if (deviceConnected && currentSpO2 != lastSentSpO2) {
                                    pCharSpO2->setValue(String(currentSpO2).c_str());
                                    pCharSpO2->notify();
                                    lastSentSpO2 = currentSpO2;
                                }
                                Serial.printf("[SpO2] R=%.3f  raw=%.1f  smooth=%.1f%%  "
                                            "PI_red=%.4f  PI_ir=%.4f\n",
                                            R, spo2Raw, ESpO2, pi_red, pi_ir);
                            } else {
                                Serial.printf("[SpO2] R=%.3f out of formula range — holding %.0f%%\n",
                                            R, ESpO2);
                            }
                        } else {
                            Serial.printf("[SpO2] R=%.3f outside physiological window — "
                                        "holding %.0f%%\n", R, ESpO2);
                        }
                    } else {
                        Serial.printf("[SpO2] Weak signal  PI_red=%.5f  PI_ir=%.5f — "
                                    "check finger position\n", pi_red, pi_ir);
                    }
                    if (currentSpO2 == 0) currentSpO2 = (int)round(ESpO2);

                }
                // Read die temperature once per SpO2 cycle regardless of signal quality
                temperature = particleSensor.readTemperature();
                // Reset accumulators for next window
                sumredrms = 0.0;
                sumirrms  = 0.0;
                spo2Count = 0;
            }
            // ── Run FFT every FFT_HOP new samples (50% sliding window) ────
            // Requires the buffer to be filled at least once (first 256 samples).
            // After that, a fresh BPM is produced every 128 samples ≈ 2.56 s.
            if (bufferFilled && fftHopCount >= FFT_HOP) {
                fftHopCount = 0;
                // Copy circular buffer chronologically: oldest sample first
                int start = sampleIndex;  // sampleIndex is the next write slot = oldest
                for (int idx = 0; idx < PULSE_SAMPLES; idx++) {
                    vReal[idx] = redArray[(start + idx) % PULSE_SAMPLES];
                    vImag[idx] = 0.0;
                }
                // arduinoFFT v1.x API — re-construct object with current arrays
                FFT = arduinoFFT(vReal, vImag, PULSE_SAMPLES, (double)SAMPLE_FREQ);
                FFT.Windowing(FFT_WIN_TYP_HAMMING, FFT_FORWARD);  // reduce spectral leakage
                FFT.Compute(FFT_FORWARD);
                FFT.ComplexToMagnitude();
                double peak   = FFT.MajorPeak();   // dominant frequency in Hz
                double newBPM = peak * 60.0;
                // Accept only physiologically plausible heart rates
                if (newBPM >= 40.0 && newBPM <= 200.0) {
                    beatsPerMinute = newBPM;

                    // IIR smooth: 70% previous + 30% new measurement
                    beatAvg = (beatAvg == 0)
                              ? (int)round(beatsPerMinute)
                              : (int)round(0.7 * (double)beatAvg + 0.3 * beatsPerMinute);

                    if (deviceConnected && beatAvg != lastSentBPM) {
                        pCharBPM->setValue(String(beatAvg).c_str());
                        pCharBPM->notify();
                        lastSentBPM = beatAvg;
                    }
                    Serial.printf("[FFT]  peak=%.3fHz  BPM=%.1f  avg=%d  SpO2=%d%%  Temp=%.1fC\n",
                                  peak, beatsPerMinute, beatAvg, currentSpO2, temperature);
                }
            }
            // ── Stress inference every 60 seconds ─────────────────────────
            // lastInferTime is a global so it survives deep-sleep wakeups.
            // If the RR buffer or BPM isn't ready yet, retry in 10 s instead
            // of waiting a full 60 s, so inference starts as soon as data allows.
            if (millis() - lastInferTime >= 60000UL) {
                computeHRVFeatures();
                if (rrCount >= 10 && beatAvg > 0) {
                    runStressInference();
                    lastInferTime = millis();          // full 60 s until next run
                } else {
                    // Not enough data — print why and retry in 10 seconds
                    Serial.printf("[AI]   Waiting — rrCount=%d (need 10)  beatAvg=%d (need >0)\n",
                                  rrCount, beatAvg);
                    lastInferTime = millis() - 50000UL; // fires again in 10 s
                }
            }
        }
        particleSensor.nextSample();   // advance FIFO read pointer
    }
    // ── 4. Heart icon animation — flashes at the current BPM rate ─────────
    if (fingerDetected && beatAvg > 0) {
        unsigned long interval = 60000UL / (unsigned long)beatAvg;
        if (now - lastHeartFlash >= interval) {
            heartState    = !heartState;
            lastHeartFlash = now;
            updateHeartIcon(heartState);
        }
    }
    // ── 5. Display refresh (only redraws changed regions) ─────────────────
    updateDisplay(now);

    // ── 6. Inactivity tracking → deep sleep ───────────────────────────────
    if (fingerDetected || isMoving || deviceConnected) {
        lastActivityTime = now;
    }
    if (now - lastActivityTime > INACTIVITY_TIMEOUT) {
        goToSleep();
    }
    // No delay() — the FIFO check loop itself naturally paces the loop body.
}