// Auto-generated by train_stress_model.py — DO NOT EDIT
// Z-score normalisation constants for the stress classifier.
// Copy this file into your Arduino sketch folder.
//
// Usage in Arduino:
//   float normalised = (raw_value - FEAT_MEAN[i]) / FEAT_STD[i];
//   input->data.int8[i] = (int8_t)(normalised / 0.024440f + -9);
//
// Feature order: RMSSD | SDNN | pNN50 | BPM | SpO2 | Activity

#pragma once

const float FEAT_MEAN[6] = { 35.856495f, 42.336397f, 17.330025f, 76.354167f, 97.420343f, 0.372549f };  // feature means  (RMSSD, SDNN, pNN50, BPM, SpO2, Activity)
const float FEAT_STD[6] = { 17.837601f, 21.929098f, 12.634811f, 14.906516f, 0.902992f, 0.621061f };  // feature std devs

constexpr float TFLITE_INPUT_SCALE      = 0.02444047f;
constexpr int   TFLITE_INPUT_ZERO_POINT = -9;

// Class index → label mapping
// 0 = Low stress   1 = Moderate stress   2 = High stress
const char* STRESS_LABELS[] = {"Low", "Moderate", "High"};
